# Generated by Django 5.0.14 on 2026-07-22 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredibilityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('disputed', 'Disputed'), ('false', 'Marked False')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('disputed', 'Disputed'), ('false', 'Marked False')], max_length=20)),
                ('reason', models.TextField(help_text='Why the status was changed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='news.newsarticle')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
