# Generated by Django 5.0.14 on 2026-07-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('news', '0003_vote_vote_one_vote_per_user_per_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('key_points', models.JSONField(default=list)),
                ('claims', models.JSONField(default=list)),
                ('summarizer_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='news.newsarticle')),
            ],
        ),
    ]
