# Generated by Django 5.0.14 on 2026-07-25 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_articlesummary'),
        ('comments', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModerationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_flagged', models.BooleanField()),
                ('score', models.PositiveSmallIntegerField()),
                ('reasons', models.JSONField(default=list)),
                ('flagger_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_flag', to='comments.comment')),
            ],
        ),
        migrations.CreateModel(
            name='ReportModerationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_flagged', models.BooleanField()),
                ('score', models.PositiveSmallIntegerField()),
                ('reasons', models.JSONField(default=list)),
                ('flagger_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_flag', to='reports.report')),
            ],
        ),
    ]
