# Generated by Django 5.0.14 on 2026-07-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('false_information', 'False information'), ('spam', 'Spam'), ('harassment', 'Harassment'), ('copyright', 'Copyright'), ('other', 'Other')], max_length=20),
        ),
    ]
